[package]
name = "rance-test"
version = "0.1.0"
authors = ["Laurent Wandrebeck <l.wandrebeck@quelquesmots.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
